name: highlight
description: Syntax highlighting for Dart with lots of languages and themes support.
version: 0.7.0
homepage: https://github.com/pd4d10/highlight

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0
  equatable: ^2.0.5
  tuple: ^2.0.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
  path: ^1.8.0
